### ISSUE TITLE
in general, suppress headings with blank data

### ISSUE THREAD

**Issue by cydharrell** [Exygy/ftrc#13]
this is not super urgent, but in general we shouldn't display a heading that has no data, i.e. the Parking or Transit headings when those cells are blank for a Courthouse row. (For non-urban courts, this information is often not present because it's not needed.)

**Comment by exygy-dev** [comment]
Story Description
===
As a FTRC user, I would like to be able to only see information about services provided at a specific court so that I am not confused by seeing empty sections for services that a Court does not offer.

Given that the Parking (Col V) display "N/A" for a given Courthouse, then the Parking section will be hidden for the Courthouse card.

Given that the Transportation (Col W) displays "N/A" for a given Courthouse, then the Transportation section will be hidden for the Courthouse card.

**Comment by jaredcwhite** [comment]
Fixed and pushed.
